# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sphinx build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install system dependencies
      run: |
        sudo make gh-pages-dependencies
    # This parses the sphinx logs and reports problems via gh-actions
    - uses: ammaraskar/sphinx-problem-matcher@master
    # Run in a dedicated step, since sometimes the other builds can
    # have extra warnings.
    - name: Build and fail on warnings
      run:
         make html SPHINXOPTS="-W --keep-going"
    - name: Sphinx Build
      run:
         make gh-pages
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/gh-pages/
        force_orphan: true
